const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const {
  PROJECT_ROOT,
  SRC_DIR,
  compileLayout,
  copyRecursiveSync,
  readFile,
} = require('./scripts/template-engine');

const SITE_BUILD_TARGET = 'gh-pages';

const args = process.argv.slice(2);
const targetArg = args.find((arg) => arg.startsWith('--target='));
const target = targetArg ? targetArg.split('=')[1] : 'tistory';

console.log(`Running template compiler target: ${target}`);

function getGhPagesCategoryTree() {
  return readFile(path.join(SRC_DIR, 'components', 'CategoryTree.html')).trim();
}

function getAutoBanner(targetName) {
  return `<!-- AUTO-GENERATED by build-html.js --target=${targetName}. Edit src/ instead. -->
<!-- Preview: run "npm run dev" — do not open this file directly in the browser. -->
`;
}

function writeOutput(htmlContent, outDir, fileName) {
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }
  const outputPath = path.join(outDir, fileName);
  fs.writeFileSync(outputPath, htmlContent, 'utf8');
  console.log(`Successfully compiled target [${target}] into [${outputPath}]`);
  return outputPath;
}

function copyBuildAssets(outDir) {
  const cssSrc = path.join(PROJECT_ROOT, 'dist', 'style.css');
  const cssDest = path.join(outDir, 'style.css');
  if (fs.existsSync(cssSrc)) {
    fs.copyFileSync(cssSrc, cssDest);
    console.log(`Copied CSS bundle to: ${cssDest}`);
  }
}

function readPostBuildTarget(html) {
  const match = html.match(/data-build-target="([^"]+)"/);
  return match?.[1] ?? null;
}

function postsNeedRebuild() {
  const postsDir = path.join(PROJECT_ROOT, 'public', 'posts');
  if (!fs.existsSync(postsDir)) return true;

  const sampleDir = fs
    .readdirSync(postsDir, { withFileTypes: true })
    .find((entry) => entry.isDirectory());
  if (!sampleDir) return true;

  const samplePath = path.join(postsDir, sampleDir.name, 'index.html');
  if (!fs.existsSync(samplePath)) return true;

  return readPostBuildTarget(readFile(samplePath)) !== SITE_BUILD_TARGET;
}

function ensurePostsBuilt() {
  console.log(`Building posts (target=${SITE_BUILD_TARGET})...`);
  execSync('node scripts/build-posts.js', {
    cwd: PROJECT_ROOT,
    stdio: 'inherit',
  });
}

function ensurePostsUpToDate() {
  if (postsNeedRebuild()) {
    ensurePostsBuilt();
  }
}

function compile() {
  const categoryTreeHtml = getGhPagesCategoryTree();
  let htmlContent;
  let outDir;
  let outFileName = target === 'tistory' ? 'skin.html' : 'index.html';

  if (target === 'tistory') {
    htmlContent = compileLayout({ target: 'tistory' });
    outDir = path.join(PROJECT_ROOT, 'dist', 'tistory');
  } else if (target === 'vite-index' || target === 'preview') {
    if (target === 'preview') {
      ensurePostsUpToDate();
    }
    htmlContent = compileLayout({ target: 'preview', categoryTreeHtml });
    htmlContent = getAutoBanner(target) + htmlContent;
    outDir = PROJECT_ROOT;
  } else if (target === 'gh-pages') {
    htmlContent = compileLayout({ target: 'gh-pages', categoryTreeHtml });
    outDir = path.join(PROJECT_ROOT, 'dist', 'gh-pages');
  } else {
    console.error(`Unknown target: ${target}`);
    process.exit(1);
  }

  writeOutput(htmlContent, outDir, outFileName);

  if (target === 'tistory' || target === 'gh-pages') {
    copyBuildAssets(outDir);
  }

  if (target === 'tistory') {
    const jsSrc = path.join(PROJECT_ROOT, 'dist', 'tistory.js');
    const jsDest = path.join(outDir, 'tistory.js');
    if (fs.existsSync(jsSrc)) {
      fs.copyFileSync(jsSrc, jsDest);
      console.log(`Copied Tistory JS bundle to: ${jsDest}`);
    } else {
      console.warn('Warning: dist/tistory.js not found. Run vite build --config vite.config.tistory.js first.');
    }
  }

  if (target === 'tistory' || target === 'gh-pages') {
    const imgDir = path.join(outDir, 'images');
    copyRecursiveSync(path.join(SRC_DIR, 'assets'), imgDir);

    if (target === 'gh-pages') {
      const assetsSrc = path.join(PROJECT_ROOT, 'dist', 'assets');
      const assetsDest = path.join(outDir, 'assets');
      copyRecursiveSync(assetsSrc, assetsDest);

      const viteImagesSrc = path.join(PROJECT_ROOT, 'dist', 'images');
      if (fs.existsSync(viteImagesSrc)) {
        copyRecursiveSync(viteImagesSrc, imgDir);
      }

      const postsSrc = path.join(PROJECT_ROOT, 'public', 'posts');
      const postsDest = path.join(outDir, 'posts');
      copyRecursiveSync(postsSrc, postsDest);

      fs.writeFileSync(path.join(outDir, '.nojekyll'), '', 'utf8');
    }

    if (target === 'tistory') {
      const xmlSrc = path.join(PROJECT_ROOT, 'skin', 'index.xml');
      const xmlDest = path.join(outDir, 'index.xml');
      if (fs.existsSync(xmlSrc)) {
        fs.copyFileSync(xmlSrc, xmlDest);
      }
    }
  }
}

compile();
