const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const { generateAllSources } = require('./scripts/generate-sources');
const {
  PROJECT_ROOT,
  SRC_DIR,
  compileLayout,
  copyRecursiveSync,
  readFile,
} = require('./scripts/template-engine');

const SITE_BUILD_TARGET = 'gh-pages';

const args = process.argv.slice(2);
const targetArg = args.find((arg) => arg.startsWith('--target='));
const target = targetArg ? targetArg.split('=')[1] : 'tistory';

console.log(`Running template compiler target: ${target}`);

generateAllSources({ log: false });

function getGhPagesCategoryTree() {
  return readFile(path.join(SRC_DIR, 'components', 'CategoryTree.html')).trim();
}

function getAutoBanner(targetName) {
  return `<!-- AUTO-GENERATED by build-html.js --target=${targetName}. Edit src/ instead. -->
<!-- Preview: run "npm run dev" — do not open this file directly in the browser. -->
`;
}

function writeOutput(htmlContent, outDir, fileName) {
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }
  const outputPath = path.join(outDir, fileName);
  fs.writeFileSync(outputPath, htmlContent, 'utf8');
  console.log(`Successfully compiled target [${target}] into [${outputPath}]`);
  return outputPath;
}

function copyBuildAssets(outDir) {
  const cssSrc = path.join(PROJECT_ROOT, 'dist', 'style.css');
  const cssDest = path.join(outDir, 'style.css');
  if (fs.existsSync(cssSrc)) {
    fs.copyFileSync(cssSrc, cssDest);
    console.log(`Copied CSS bundle to: ${cssDest}`);
  }
}

function readPostBuildTarget(html) {
  const match = html.match(/data-build-target="([^"]+)"/);
  return match?.[1] ?? null;
}

function postsNeedRebuild() {
  const postsDir = path.join(PROJECT_ROOT, 'public', 'posts');
  if (!fs.existsSync(postsDir)) return true;

  const sampleDir = fs
    .readdirSync(postsDir, { withFileTypes: true })
    .find((entry) => entry.isDirectory());
  if (!sampleDir) return true;

  const samplePath = path.join(postsDir, sampleDir.name, 'index.html');
  if (!fs.existsSync(samplePath)) return true;

  return readPostBuildTarget(readFile(samplePath)) !== SITE_BUILD_TARGET;
}

function ensurePostsBuilt() {
  console.log(`Building posts (target=${SITE_BUILD_TARGET})...`);
  execSync('node scripts/build-posts.js', {
    cwd: PROJECT_ROOT,
    stdio: 'inherit',
  });
}

function ensurePostsUpToDate() {
  if (postsNeedRebuild()) {
    ensurePostsBuilt();
  }
}

/** Tistory serves skin files as flat images/* — nested badges/dark/ paths 404 on many blogs. */
function flattenTistoryImages(imgDir) {
  if (!fs.existsSync(imgDir)) return 0;

  let flattened = 0;

  function walk(dir) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
        continue;
      }

      if (fullPath === path.join(imgDir, entry.name)) continue;

      const dest = path.join(imgDir, entry.name);
      if (!fs.existsSync(dest)) {
        fs.copyFileSync(fullPath, dest);
        flattened += 1;
      }
    }
  }

  walk(imgDir);

  for (const entry of fs.readdirSync(imgDir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      fs.rmSync(path.join(imgDir, entry.name), { recursive: true, force: true });
    }
  }

  return flattened;
}

function writeTistoryPreviewGif(outDir) {
  const customPreview = path.join(SRC_DIR, 'assets', 'preview.gif');
  const previewDest = path.join(outDir, 'preview.gif');

  if (fs.existsSync(customPreview)) {
    fs.copyFileSync(customPreview, previewDest);
    console.log(`Copied preview.gif to: ${previewDest}`);
    return;
  }

  const placeholderGif = Buffer.from('R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7', 'base64');
  fs.writeFileSync(previewDest, placeholderGif);
  console.log(`Wrote placeholder preview.gif to: ${previewDest}`);
}

const TISTORY_PREVIEW_FILES = ['preview.gif', 'preview256.jpg', 'preview560.jpg', 'preview1600.jpg'];

function ensureTistoryPreviews() {
  const script = path.join(PROJECT_ROOT, 'scripts', 'generate-tistory-previews.py');
  const profile = path.join(SRC_DIR, 'assets', 'profile.png');
  const greeting = path.join(SRC_DIR, 'assets', 'greeting.gif');
  const skinDir = path.join(PROJECT_ROOT, 'skin');

  if (!fs.existsSync(script) || !fs.existsSync(profile) || !fs.existsSync(greeting)) return;

  const sourceMtime = Math.max(fs.statSync(profile).mtimeMs, fs.statSync(greeting).mtimeMs);
  const outputs = TISTORY_PREVIEW_FILES.map((name) => path.join(skinDir, name));
  const needsRegen =
    outputs.some((filePath) => !fs.existsSync(filePath)) ||
    outputs.some((filePath) => fs.existsSync(filePath) && fs.statSync(filePath).mtimeMs < sourceMtime);

  if (!needsRegen) return;

  try {
    execSync(`python "${script}"`, { cwd: PROJECT_ROOT, stdio: 'inherit' });
  } catch {
    console.warn('Warning: could not generate Tistory previews (greeting.gif + profile.png)');
  }
}

function copyTistoryPreviews(outDir) {
  const skinDir = path.join(PROJECT_ROOT, 'skin');
  let copied = 0;

  for (const name of TISTORY_PREVIEW_FILES) {
    const src = path.join(skinDir, name);
    if (!fs.existsSync(src)) continue;
    fs.copyFileSync(src, path.join(outDir, name));
    copied += 1;
  }

  if (copied > 0) {
    console.log(`Copied ${copied} Tistory preview file(s) from skin/ to dist/tistory/`);
    return;
  }

  writeTistoryPreviewGif(outDir);
}

function compile() {
  const categoryTreeHtml = getGhPagesCategoryTree();
  let htmlContent;
  let outDir;
  let outFileName = target === 'tistory' ? 'skin.html' : 'index.html';

  if (target === 'tistory') {
    ensureTistoryPreviews();
    htmlContent = compileLayout({ target: 'tistory' });
    outDir = path.join(PROJECT_ROOT, 'dist', 'tistory');
  } else if (target === 'vite-index' || target === 'preview') {
    if (target === 'preview') {
      ensurePostsUpToDate();
    }
    htmlContent = compileLayout({ target: 'preview', categoryTreeHtml });
    htmlContent = getAutoBanner(target) + htmlContent;
    outDir = PROJECT_ROOT;
  } else if (target === 'gh-pages') {
    htmlContent = compileLayout({ target: 'gh-pages', categoryTreeHtml });
    outDir = path.join(PROJECT_ROOT, 'dist', 'gh-pages');
  } else {
    console.error(`Unknown target: ${target}`);
    process.exit(1);
  }

  writeOutput(htmlContent, outDir, outFileName);

  if (target === 'tistory' || target === 'gh-pages') {
    copyBuildAssets(outDir);
  }

  if (target === 'tistory') {
    const jsSrc = path.join(PROJECT_ROOT, 'dist', 'tistory.js');
    const jsDest = path.join(outDir, 'images', 'tistory.js');
    if (fs.existsSync(jsSrc)) {
      fs.mkdirSync(path.join(outDir, 'images'), { recursive: true });
      fs.copyFileSync(jsSrc, jsDest);
      console.log(`Copied Tistory JS bundle to: ${jsDest}`);
    } else {
      console.warn('Warning: dist/tistory.js not found. Run vite build --config vite.config.tistory.js first.');
    }

    copyTistoryPreviews(outDir);
  }

  if (target === 'tistory' || target === 'gh-pages') {
    const imgDir = path.join(outDir, 'images');
    copyRecursiveSync(path.join(SRC_DIR, 'assets'), imgDir);

    if (target === 'gh-pages') {
      const assetsSrc = path.join(PROJECT_ROOT, 'dist', 'assets');
      const assetsDest = path.join(outDir, 'assets');
      copyRecursiveSync(assetsSrc, assetsDest);

      const viteImagesSrc = path.join(PROJECT_ROOT, 'dist', 'images');
      if (fs.existsSync(viteImagesSrc)) {
        copyRecursiveSync(viteImagesSrc, imgDir);
      }

      const postsSrc = path.join(PROJECT_ROOT, 'public', 'posts');
      const postsDest = path.join(outDir, 'posts');
      copyRecursiveSync(postsSrc, postsDest);

      fs.writeFileSync(path.join(outDir, '.nojekyll'), '', 'utf8');
    }

    if (target === 'tistory') {
      // Self-hosted fonts / FA webfonts from the Vite CSS bundle
      const viteImagesSrc = path.join(PROJECT_ROOT, 'dist', 'images');
      if (fs.existsSync(viteImagesSrc)) {
        copyRecursiveSync(viteImagesSrc, imgDir);
      }

      const xmlSrc = path.join(PROJECT_ROOT, 'skin', 'index.xml');
      const xmlDest = path.join(outDir, 'index.xml');
      if (fs.existsSync(xmlSrc)) {
        fs.copyFileSync(xmlSrc, xmlDest);
      }

      const flattened = flattenTistoryImages(imgDir);
      if (flattened > 0) {
        console.log(`Flattened ${flattened} nested image(s) into images/ (Tistory flat paths).`);
      }
    }
  }
}

compile();
