import { defineConfig } from 'vite';
import { resolve } from 'path';

/** Local dev: production HTML paths are rewritten to Vite sources. */
function devAssetFallback() {
  return {
    name: 'dev-asset-fallback',
    configureServer(server) {
      server.middlewares.use((req, _res, next) => {
        const url = req.url?.split('?')[0];
        if (url === '/assets/main.js') req.url = '/src/main.js';
        else if (url === '/style.css') req.url = '/src/style.css';
        else if (url?.startsWith('/images/')) {
          req.url = `/src/assets/${url.slice('/images/'.length)}`;
        }
        next();
      });
    },
  };
}

// index.html is gitignored and generated by `npm run build:html:vite-index`.
export default defineConfig({
  plugins: [devAssetFallback()],
  build: {
    outDir: 'dist',
    assetsDir: 'images',
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
      },
      output: {
        assetFileNames: (assetInfo) => {
          if (assetInfo.name === 'main.css' || assetInfo.name === 'style.css') {
            return 'style.css';
          }
          return 'images/[name].[ext]';
        },
        entryFileNames: 'assets/[name].js',
        chunkFileNames: 'assets/[name].js',
      },
    },
  },
});
