const fs = require('fs');
const path = require('path');
const { escapeHtml } = require(path.join(__dirname, '..', 'src', 'utils', 'escape-html.cjs'));

const PROJECT_ROOT = path.join(__dirname, '..');
const SRC_DIR = path.join(PROJECT_ROOT, 'src');
const CATEGORIES_PATH = path.join(SRC_DIR, 'data', 'categories.json');
const ARTICLE_SOURCE_PATH = path.join(SRC_DIR, 'templates', 'article-shell.source.html');

const OUTPUTS = {
  categoryTree: path.join(SRC_DIR, 'components', 'CategoryTree.html'),
  articlePage: path.join(SRC_DIR, 'templates', 'article-page.html'),
};

const GENERATED_BANNER = (source) =>
  `<!-- AUTO-GENERATED by scripts/generate-sources.js — edit ${source} instead. -->\n`;

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function renderCategoryLeaf(id, labels) {
  const label = labels[id];
  if (!label) {
    throw new Error(`Unknown category id in tree: ${id}`);
  }

  return `  <li class="category-tree__item category-tree__item--leaf">
    <a href="#category-${escapeHtml(id)}" data-category-id="${escapeHtml(id)}" data-category-label="${escapeHtml(label)}" class="category-tree__link category-tree__link--branch-level">
      <i class="fa-solid fa-folder text-accentAmber w-4 text-center shrink-0" aria-hidden="true"></i>
      <span class="category-tree__label">${escapeHtml(label)}</span>
      <span class="category-tree__count"></span>
    </a>
  </li>`;
}

function renderCategoryChild(id, labels) {
  const label = labels[id];
  if (!label) {
    throw new Error(`Unknown category id in tree: ${id}`);
  }

  return `      <li class="category-tree__item category-tree__item--leaf">
        <a href="#category-${escapeHtml(id)}" data-category-id="${escapeHtml(id)}" data-category-label="${escapeHtml(label)}" class="category-tree__link category-tree__link--child">
          <i class="fa-solid fa-folder-open text-accentAmber w-4 text-center shrink-0" aria-hidden="true"></i>
          <span class="category-tree__label">${escapeHtml(label)}</span>
          <span class="category-tree__count"></span>
        </a>
      </li>`;
}

function renderCategoryBranch(node, labels) {
  const isOpen = node.defaultOpen !== false;
  const openClass = isOpen ? ' is-open' : '';
  const ariaExpanded = isOpen ? 'true' : 'false';
  const children = node.children.map((id) => renderCategoryChild(id, labels)).join('\n');

  return `  <li class="category-tree__item category-tree__item--branch${openClass}" data-category-branch>
    <div class="category-tree__row">
      <a href="#" class="category-tree__link category-tree__link--branch" aria-expanded="${ariaExpanded}">
        <i class="fa-solid fa-folder text-accentAmber w-4 text-center shrink-0" aria-hidden="true"></i>
        <span class="category-tree__label">${escapeHtml(node.branch)}</span>
        <span class="category-tree__count"></span>
      </a>
    </div>
    <ul class="category-tree__children list-none">
${children}
    </ul>
  </li>`;
}

function generateCategoryTreeHtml() {
  const { labels, tree, rootLabel = "Bulldog's Posts" } = readJson(CATEGORIES_PATH);
  if (!Array.isArray(tree) || !tree.length) {
    throw new Error('categories.json must include a non-empty "tree" array');
  }

  const items = tree.map((node) => {
    if (typeof node === 'string') {
      return renderCategoryLeaf(node, labels);
    }
    if (node.branch && Array.isArray(node.children)) {
      return renderCategoryBranch(node, labels);
    }
    throw new Error(`Invalid category tree node: ${JSON.stringify(node)}`);
  });

  return `${GENERATED_BANNER('src/data/categories.json')}<ul class="category-tree sidebar-menu list-none" data-category-tree>
  <li class="category-tree__item category-tree__item--root category-tree__item--branch is-open" data-category-root data-category-branch>
    <div class="category-tree__row">
      <a href="#" class="category-tree__link category-tree__link--root category-tree__link--branch" aria-expanded="true">
        <i class="fa-solid fa-folder text-accentAmber w-4 text-center shrink-0" aria-hidden="true"></i>
        <span class="category-tree__label">${escapeHtml(rootLabel)}</span>
        <span class="category-tree__count"></span>
      </a>
    </div>
    <ul class="category-tree__children list-none">
${items.join('\n\n')}
    </ul>
  </li>
</ul>
`;
}

const ARTICLE_TOKENS = {
  CATEGORY_LINK: '{{categoryLink}}',
  CATEGORY_LABEL: '{{categoryLabel}}',
  TITLE: '{{title}}',
  DATE: '{{date}}',
  AUTHOR: '{{author}}',
  TAGS: '{{tagsHtml}}',
  THUMBNAIL: '{{thumbnailHtml}}',
  CONTENT: '{{content}}',
  POST_NAV: `{{prevNavHtml}}\n    {{nextNavHtml}}`,
};

function generateArticlePage() {
  let html = fs.readFileSync(ARTICLE_SOURCE_PATH, 'utf8').trim();
  for (const [token, value] of Object.entries(ARTICLE_TOKENS)) {
    html = html.split(`@@${token}@@`).join(value);
  }
  return `${GENERATED_BANNER('src/templates/article-shell.source.html')}${html}\n`;
}

function writeIfChanged(filePath, content) {
  const previous = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : null;
  if (previous === content) return false;
  fs.writeFileSync(filePath, content, 'utf8');
  return true;
}

function generateAllSources({ log = true } = {}) {
  const categoryTree = generateCategoryTreeHtml();
  const articlePage = generateArticlePage();

  const changed = [
    writeIfChanged(OUTPUTS.categoryTree, categoryTree) && OUTPUTS.categoryTree,
    writeIfChanged(OUTPUTS.articlePage, articlePage) && OUTPUTS.articlePage,
  ].filter(Boolean);

  if (log) {
    if (changed.length) {
      changed.forEach((filePath) => {
        console.log(`Generated: ${path.relative(PROJECT_ROOT, filePath)}`);
      });
    } else {
      console.log('Generated sources are up to date.');
    }
  }

  return { changed };
}

if (require.main === module) {
  generateAllSources();
}

module.exports = { generateAllSources, generateCategoryTreeHtml, generateArticlePage };
