const fs = require('fs');
const path = require('path');
const { escapeHtml } = require(path.join(__dirname, '..', 'src', 'utils', 'escape-html.cjs'));

const PROJECT_ROOT = path.join(__dirname, '..');
const SRC_DIR = path.join(PROJECT_ROOT, 'src');
const CATEGORIES_PATH = path.join(SRC_DIR, 'data', 'categories.json');
const ARTICLE_SOURCE_PATH = path.join(SRC_DIR, 'templates', 'article-shell.source.html');

const OUTPUTS = {
  categoryTree: path.join(SRC_DIR, 'components', 'CategoryTree.html'),
  articleMustache: path.join(SRC_DIR, 'templates', 'article-page.html'),
  articleTistory: path.join(SRC_DIR, 'components', 'Article.html'),
};

const GENERATED_BANNER = (source) =>
  `<!-- AUTO-GENERATED by scripts/generate-sources.js — edit ${source} instead. -->\n`;

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function renderCategoryLeaf(id, labels) {
  const label = labels[id];
  if (!label) {
    throw new Error(`Unknown category id in tree: ${id}`);
  }

  return `  <li class="category-tree__item category-tree__item--leaf">
    <a href="#category-${escapeHtml(id)}" data-category-id="${escapeHtml(id)}" data-category-label="${escapeHtml(label)}" class="category-tree__link category-tree__link--branch-level">
      <i class="fa-regular fa-folder text-accentAmber w-4 text-center shrink-0" aria-hidden="true"></i>
      <span class="category-tree__label">${escapeHtml(label)}</span>
      <span class="category-tree__count"></span>
    </a>
  </li>`;
}

function renderCategoryChild(id, labels) {
  const label = labels[id];
  if (!label) {
    throw new Error(`Unknown category id in tree: ${id}`);
  }

  return `      <li class="category-tree__item category-tree__item--leaf">
        <a href="#category-${escapeHtml(id)}" data-category-id="${escapeHtml(id)}" data-category-label="${escapeHtml(label)}" class="category-tree__link category-tree__link--child">
          <i class="fa-regular fa-folder-open text-accentAmber w-4 text-center shrink-0" aria-hidden="true"></i>
          <span class="category-tree__label">${escapeHtml(label)}</span>
          <span class="category-tree__count"></span>
        </a>
      </li>`;
}

function renderCategoryBranch(node, labels) {
  const isOpen = node.defaultOpen !== false;
  const openClass = isOpen ? ' is-open' : '';
  const ariaExpanded = isOpen ? 'true' : 'false';
  const children = node.children.map((id) => renderCategoryChild(id, labels)).join('\n');

  return `  <li class="category-tree__item category-tree__item--branch${openClass}" data-category-branch>
    <div class="category-tree__row">
      <a href="#" class="category-tree__link category-tree__link--branch" aria-expanded="${ariaExpanded}">
        <i class="fa-regular fa-folder text-accentAmber w-4 text-center shrink-0" aria-hidden="true"></i>
        <span class="category-tree__label">${escapeHtml(node.branch)}</span>
        <span class="category-tree__count"></span>
      </a>
    </div>
    <ul class="category-tree__children list-none">
${children}
    </ul>
  </li>`;
}

function generateCategoryTreeHtml() {
  const { labels, tree, rootLabel = "Bulldog's Posts" } = readJson(CATEGORIES_PATH);
  if (!Array.isArray(tree) || !tree.length) {
    throw new Error('categories.json must include a non-empty "tree" array');
  }

  const items = tree.map((node) => {
    if (typeof node === 'string') {
      return renderCategoryLeaf(node, labels);
    }
    if (node.branch && Array.isArray(node.children)) {
      return renderCategoryBranch(node, labels);
    }
    throw new Error(`Invalid category tree node: ${JSON.stringify(node)}`);
  });

  return `${GENERATED_BANNER('src/data/categories.json')}<ul class="category-tree sidebar-menu list-none" data-category-tree>
  <li class="category-tree__item category-tree__item--root category-tree__item--branch is-open" data-category-root data-category-branch>
    <div class="category-tree__row">
      <a href="#" class="category-tree__link category-tree__link--root category-tree__link--branch" aria-expanded="true">
        <i class="fa-solid fa-folder text-accentAmber w-4 text-center shrink-0" aria-hidden="true"></i>
        <span class="category-tree__label">${escapeHtml(rootLabel)}</span>
        <span class="category-tree__count"></span>
      </a>
    </div>
    <ul class="category-tree__children list-none">
${items.join('\n\n')}
    </ul>
  </li>
</ul>
`;
}

const ARTICLE_VARIANTS = {
  mustache: {
    ARTICLE_ROOT_ATTRS: '',
    CATEGORY_LINK: '{{categoryLink}}',
    CATEGORY_LABEL: '{{categoryLabel}}',
    TITLE: '{{title}}',
    DATE: '{{date}}',
    AUTHOR: '{{author}}',
    TAGS: '{{tagsHtml}}',
    THUMBNAIL: '{{thumbnailHtml}}',
    CONTENT: '{{content}}',
    POST_NAV: `{{prevNavHtml}}\n    {{nextNavHtml}}`,
    WRAPPER_START: '',
    WRAPPER_END: '',
  },
  tistory: {
    ARTICLE_ROOT_ATTRS: '',
    CATEGORY_LINK: '[##_article_rep_category_link_##]',
    CATEGORY_LABEL: '[##_article_rep_category_##]',
    TITLE: '[##_article_rep_title_##]',
    DATE: '[##_article_rep_date_##]',
    AUTHOR: '[##_blogger_##]',
    TAGS: `<s_tag_label>
      <div class="article-tags">
        [##_tag_label_rep_##]
      </div>
    </s_tag_label>`,
    THUMBNAIL: '',
    CONTENT: '[##_article_rep_desc_##]',
    POST_NAV: `<s_article_prev>
        <a href="[##_article_prev_link_##]" class="article-post-nav__card article-post-nav__card--prev">
          <span class="article-post-nav__icon" aria-hidden="true"><i class="fa-solid fa-arrow-left"></i></span>
          <span class="article-post-nav__text">
            <span class="article-post-nav__label">이전 포스트</span>
            <span class="article-post-nav__title">[##_article_prev_title_##]</span>
          </span>
        </a>
      </s_article_prev>
      <s_article_next>
        <a href="[##_article_next_link_##]" class="article-post-nav__card article-post-nav__card--next">
          <span class="article-post-nav__text">
            <span class="article-post-nav__label">다음 포스트</span>
            <span class="article-post-nav__title">[##_article_next_title_##]</span>
          </span>
          <span class="article-post-nav__icon" aria-hidden="true"><i class="fa-solid fa-arrow-right"></i></span>
        </a>
      </s_article_next>`,
    WRAPPER_START: `<s_permalink_article_rep>
<main id="article-content" class="article-content-host flex-1 min-h-screen w-full flex justify-center">
  <div class="main-content-inner w-full max-w-[1200px] flex flex-col py-10 px-[60px] max-md:px-5 max-md:pt-20">`,
    WRAPPER_END: `  </div>
</main>
</s_permalink_article_rep>`,
  },
};

function applyArticleVariant(source, variant) {
  let html = source;
  for (const [token, value] of Object.entries(variant)) {
    if (token === 'WRAPPER_START' || token === 'WRAPPER_END' || token === 'ARTICLE_ROOT_ATTRS') {
      continue;
    }
    html = html.split(`@@${token}@@`).join(value);
  }

  const rootAttrs = variant.ARTICLE_ROOT_ATTRS;
  if (rootAttrs) {
    html = html.replace(` @@ARTICLE_ROOT_ATTRS@@`, ` ${rootAttrs}`);
  } else {
    html = html.replace(' @@ARTICLE_ROOT_ATTRS@@', '');
  }

  return `${variant.WRAPPER_START}${html}${variant.WRAPPER_END}`;
}

function generateArticleShells() {
  const source = fs.readFileSync(ARTICLE_SOURCE_PATH, 'utf8').trim();
  const mustache = applyArticleVariant(source, ARTICLE_VARIANTS.mustache);
  const tistory = applyArticleVariant(source, ARTICLE_VARIANTS.tistory);

  return {
    mustache: `${GENERATED_BANNER('src/templates/article-shell.source.html')}${mustache}\n`,
    tistory: `${GENERATED_BANNER('src/templates/article-shell.source.html')}${tistory}\n`,
  };
}

function writeIfChanged(filePath, content) {
  const previous = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : null;
  if (previous === content) return false;
  fs.writeFileSync(filePath, content, 'utf8');
  return true;
}

function generateAllSources({ log = true } = {}) {
  const categoryTree = generateCategoryTreeHtml();
  const articles = generateArticleShells();

  const changed = [
    writeIfChanged(OUTPUTS.categoryTree, categoryTree) && OUTPUTS.categoryTree,
    writeIfChanged(OUTPUTS.articleMustache, articles.mustache) && OUTPUTS.articleMustache,
    writeIfChanged(OUTPUTS.articleTistory, articles.tistory) && OUTPUTS.articleTistory,
  ].filter(Boolean);

  if (log) {
    if (changed.length) {
      changed.forEach((filePath) => {
        console.log(`Generated: ${path.relative(PROJECT_ROOT, filePath)}`);
      });
    } else {
      console.log('Generated sources are up to date.');
    }
  }

  return { changed };
}

if (require.main === module) {
  generateAllSources();
}

module.exports = { generateAllSources, generateCategoryTreeHtml, generateArticleShells };
